package common.geo;

import java.util.HashMap;
import java.util.Map;

public class CountryAbbreviation {
    public static final Map<String, String> long2Short = new HashMap<String, String>() {
        {
            put("ANDORRA", "AD");
            put("UNITED ARAB EMIRATES", "AE");
            put("AFGHANISTAN", "AF");
            put("ANTIGUA AND BARBUDA", "AG");
            put("ANGUILLA", "AI");
            put("ALBANIA", "AL");
            put("ARMENIA", "AM");
            put("NETHERLANDS ANTILLES", "AN");
            put("ANGOLA", "AO");
            put("ANTARCTICA", "AQ");
            put("ARGENTINA", "AR");
            put("AMERICAN SAMOA", "AS");
            put("AUSTRIA", "AT");
            put("AUSTRALIA", "AU");
            put("ARUBA", "AW");
            put("AZERBAIJAN", "AZ");
            put("BOSNIA AND HERZEGOVINA", "BA");
            put("BARBADOS", "BB");
            put("BANGLADESH", "BD");
            put("BELGIUM", "BE");
            put("BURKINA FASO", "BF");
            put("BULGARIA", "BG");
            put("BAHRAIN", "BH");
            put("BURUNDI", "BI");
            put("BENIN", "BJ");
            put("BERMUDA", "BM");
            put("BRUNEI DARUSSALAM", "BN");
            put("BOLIVIA", "BO");
            put("BRAZIL", "BR");
            put("BAHAMAS", "BS");
            put("BHUTAN", "BT");
            put("BOUVET ISLAND", "BV");
            put("BOTSWANA", "BW");
            put("BELARUS", "BY");
            put("BELIZE", "BZ");
            put("CANADA", "CA");
            put("COCOS (KEELING) ISLANDS", "CC");
            put("CENTRAL AFRICAN REPUBLIC", "CF");
            put("CONGO", "CG");
            put("SWITZERLAND", "CH");
            put("COTE D'IVOIRE (IVORY COAST)", "CI");
            put("COOK ISLANDS", "CK");
            put("CHILE", "CL");
            put("CAMEROON", "CM");
            put("CHINA", "CN");
            put("COLOMBIA", "CO");
            put("COSTA RICA", "CR");
            put("CZECHOSLOVAKIA (FORMER)", "CS");
            put("CUBA", "CU");
            put("CAPE VERDE", "CV");
            put("CHRISTMAS ISLAND", "CX");
            put("CYPRUS", "CY");
            put("CZECH REPUBLIC", "CZ");
            put("GERMANY", "DE");
            put("DJIBOUTI", "DJ");
            put("DENMARK", "DK");
            put("DOMINICA", "DM");
            put("DOMINICAN REPUBLIC", "DO");
            put("ALGERIA", "DZ");
            put("ECUADOR", "EC");
            put("ESTONIA", "EE");
            put("EGYPT", "EG");
            put("WESTERN SAHARA", "EH");
            put("ERITREA", "ER");
            put("SPAIN", "ES");
            put("ETHIOPIA", "ET");
            put("FINLAND", "FI");
            put("FIJI", "FJ");
            put("FALKLAND ISLANDS (MALVINAS)", "FK");
            put("MICRONESIA", "FM");
            put("FAROE ISLANDS", "FO");
            put("FRANCE", "FR");
            put("FRANCE, METROPOLITAN", "FX");
            put("GABON", "GA");
            put("GREAT BRITAIN (UK)", "GB");
            put("GRENADA", "GD");
            put("GEORGIA", "GE");
            put("FRENCH GUIANA", "GF");
            put("GHANA", "GH");
            put("GIBRALTAR", "GI");
            put("GREENLAND", "GL");
            put("GAMBIA", "GM");
            put("GUINEA", "GN");
            put("GUADELOUPE", "GP");
            put("EQUATORIAL GUINEA", "GQ");
            put("GREECE", "GR");
            put("S. GEORGIA AND S. SANDWICH ISLS.", "GS");
            put("GUATEMALA", "GT");
            put("GUAM", "GU");
            put("GUINEA-BISSAU", "GW");
            put("GUYANA", "GY");
            put("HONG KONG", "HK");
            put("HEARD AND MCDONALD ISLANDS", "HM");
            put("HONDURAS", "HN");
            put("CROATIA (HRVATSKA)", "HR");
            put("HAITI", "HT");
            put("HUNGARY", "HU");
            put("INDONESIA", "ID");
            put("IRELAND", "IE");
            put("ISRAEL", "IL");
            put("INDIA", "IN");
            put("BRITISH INDIAN OCEAN TERRITORY", "IO");
            put("IRAQ", "IQ");
            put("IRAN", "IR");
            put("ICELAND", "IS");
            put("ITALY", "IT");
            put("JAMAICA", "JM");
            put("JORDAN", "JO");
            put("JAPAN", "JP");
            put("KENYA", "KE");
            put("KYRGYZSTAN", "KG");
            put("CAMBODIA", "KH");
            put("KIRIBATI", "KI");
            put("COMOROS", "KM");
            put("SAINT KITTS AND NEVIS", "KN");
            put("KOREA (NORTH)", "KP");
            put("KOREA (SOUTH)", "KR");
            put("KUWAIT", "KW");
            put("CAYMAN ISLANDS", "KY");
            put("KAZAKHSTAN", "KZ");
            put("LAOS", "LA");
            put("LEBANON", "LB");
            put("SAINT LUCIA", "LC");
            put("LIECHTENSTEIN", "LI");
            put("SRI LANKA", "LK");
            put("LIBERIA", "LR");
            put("LESOTHO", "LS");
            put("LITHUANIA", "LT");
            put("LUXEMBOURG", "LU");
            put("LATVIA", "LV");
            put("LIBYA", "LY");
            put("MOROCCO", "MA");
            put("MONACO", "MC");
            put("MOLDOVA", "MD");
            put("MADAGASCAR", "MG");
            put("MARSHALL ISLANDS", "MH");
            put("MACEDONIA", "MK");
            put("MALI", "ML");
            put("MYANMAR", "MM");
            put("MONGOLIA", "MN");
            put("MACAU", "MO");
            put("NORTHERN MARIANA ISLANDS", "MP");
            put("MARTINIQUE", "MQ");
            put("MAURITANIA", "MR");
            put("MONTSERRAT", "MS");
            put("MALTA", "MT");
            put("MAURITIUS", "MU");
            put("MALDIVES", "MV");
            put("MALAWI", "MW");
            put("MEXICO", "MX");
            put("MALAYSIA", "MY");
            put("MOZAMBIQUE", "MZ");
            put("NAMIBIA", "NA");
            put("NEW CALEDONIA", "NC");
            put("NIGER", "NE");
            put("NORFOLK ISLAND", "NF");
            put("NIGERIA", "NG");
            put("NICARAGUA", "NI");
            put("NETHERLANDS", "NL");
            put("NORWAY", "NO");
            put("NEPAL", "NP");
            put("NAURU", "NR");
            put("NEUTRAL ZONE", "NT");
            put("NIUE", "NU");
            put("NEW ZEALAND (AOTEAROA)", "NZ");
            put("OMAN", "OM");
            put("PANAMA", "PA");
            put("PERU", "PE");
            put("FRENCH POLYNESIA", "PF");
            put("PAPUA NEW GUINEA", "PG");
            put("PHILIPPINES", "PH");
            put("PAKISTAN", "PK");
            put("POLAND", "PL");
            put("ST. PIERRE AND MIQUELON", "PM");
            put("PITCAIRN", "PN");
            put("PUERTO RICO", "PR");
            put("PORTUGAL", "PT");
            put("PALAU", "PW");
            put("PARAGUAY", "PY");
            put("QATAR", "QA");
            put("REUNION", "RE");
            put("ROMANIA", "RO");
            put("RUSSIAN FEDERATION", "RU");
            put("RWANDA", "RW");
            put("SAUDI ARABIA", "SA");
            put("SOLOMON ISLANDS", "SB");
            put("SEYCHELLES", "SC");
            put("SUDAN", "SD");
            put("SWEDEN", "SE");
            put("SINGAPORE", "SG");
            put("ST. HELENA", "SH");
            put("SLOVENIA", "SI");
            put("SVALBARD AND JAN MAYEN ISLANDS", "SJ");
            put("SLOVAK REPUBLIC", "SK");
            put("SIERRA LEONE", "SL");
            put("SAN MARINO", "SM");
            put("SENEGAL", "SN");
            put("SOMALIA", "SO");
            put("SURINAME", "SR");
            put("SAO TOME AND PRINCIPE", "ST");
            put("USSR (FORMER)", "SU");
            put("EL SALVADOR", "SV");
            put("SYRIA", "SY");
            put("SWAZILAND", "SZ");
            put("TURKS AND CAICOS ISLANDS", "TC");
            put("CHAD", "TD");
            put("FRENCH SOUTHERN TERRITORIES", "TF");
            put("TOGO", "TG");
            put("THAILAND", "TH");
            put("TAJIKISTAN", "TJ");
            put("TOKELAU", "TK");
            put("TURKMENISTAN", "TM");
            put("TUNISIA", "TN");
            put("TONGA", "TO");
            put("EAST TIMOR", "TP");
            put("TURKEY", "TR");
            put("TRINIDAD AND TOBAGO", "TT");
            put("TUVALU", "TV");
            put("TAIWAN", "TW");
            put("TANZANIA", "TZ");
            put("UKRAINE", "UA");
            put("UGANDA", "UG");
            put("UNITED KINGDOM", "UK");
            put("US MINOR OUTLYING ISLANDS", "UM");
            put("UNITED STATES", "US");
            put("URUGUAY", "UY");
            put("UZBEKISTAN", "UZ");
            put("VATICAN CITY STATE (HOLY SEE)", "VA");
            put("SAINT VINCENT AND THE GRENADINES", "VC");
            put("VENEZUELA", "VE");
            put("VIRGIN ISLANDS (BRITISH)", "VG");
            put("VIRGIN ISLANDS (U.S.)", "VI");
            put("VIET NAM", "VN");
            put("VANUATU", "VU");
            put("WALLIS AND FUTUNA ISLANDS", "WF");
            put("SAMOA", "WS");
            put("YEMEN", "YE");
            put("MAYOTTE", "YT");
            put("YUGOSLAVIA", "YU");
            put("SOUTH AFRICA", "ZA");
            put("ZAMBIA", "ZM");
            put("ZAIRE", "ZR");
            put("ZIMBABWE", "ZW");
        }
    };
    
    public static final Map<String, String> short2Long = new HashMap<String, String>() {
        {
            for(Map.Entry<String, String> entry : long2Short.entrySet()) {
                put(entry.getValue(), entry.getKey());
            }
        }
    };
}
