<h4>ACCEPTANCE OF TERMS</h4>
<p>
1Mile welcomes you. 1Mile provides its service to you subject to the following Terms of Service ("TOS"), which may be updated by us from time to time without notice to you. You can review the most current version of the TOS at any time at: http://info.yahoo.com/legal/us/yahoo/utos/utos-173.html . In addition, when using particular 1Mile owned or operated services, you and 1Mile shall be subject to any posted guidelines or rules applicable to such services, which may be posted from time to time. All such guidelines or rules (including but not limited to our Spam Policy) are hereby incorporated by reference into the TOS. 1Mile may also offer other services that are governed by different Terms of Service. For instance, different terms apply to homesteaders on 1Mile GeoCities or members of AT&T 1Mile Dial or AT&T 1Mile High Speed.
</p>

<h4>DESCRIPTION OF SERVICE</h4>
<p>1Mile provides users with access to a rich collection of resources, including various communications tools, forums, shopping services, search services, personalized content and branded programming through its network of properties which may be accessed through any various medium or device now known or hereafter developed (the "Service"). You also understand and agree that the Service may include advertisements and that these advertisements are necessary for 1Mile to provide the Service. You also understand and agree that the Service may include certain communications from 1Mile, such as service announcements, administrative messages and the 1Mile Newsletter, and that these communications are considered part of 1Mile membership and you will not be able to opt out of receiving them. Unless explicitly stated otherwise, any new features that augment or enhance the current Service, including the release of new 1Mile properties, shall be subject to the TOS. You understand and agree that the Service is provided "AS-IS" and that 1Mile assumes no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings. You are responsible for obtaining access to the Service, and that access may involve third-party fees (such as Internet service provider or airtime charges). You are responsible for those fees, including those fees associated with the display or delivery of advertisements. In addition, you must provide and are responsible for all equipment necessary to access the Service.
</p><p>
Please be aware that 1Mile has created certain areas on the Service that contain adult or mature content. You must be at least 18 years of age to access and view such areas.
</p>

<h4>
YOUR REGISTRATION OBLIGATIONS</h4>
<p>
In consideration of your use of the Service, you represent that you are of legal age to form a binding contract and are not a person barred from receiving services under the laws of the United States or other applicable jurisdiction. You also agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Service's registration form (the "Registration Data") and (b) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or 1Mile has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, 1Mile has the right to suspend or terminate your account and refuse any and all current or future use of the Service (or any portion thereof). 1Mile is concerned about the safety and privacy of all its users, particularly children. For this reason, parents of children under the age of 13 who wish to allow their children access to the Service must create a 1Mile Family Account. When you create a 1Mile Family Account and add your child to the account, you certify that you are at least 18 years old and that you are the legal guardian of the child/children listed on the 1Mile Family Account. By adding a child to your 1Mile Family Account, you also give your child permission to access many areas of the Service, including, email, message boards and instant messaging (among others). Please remember that the Service is designed to appeal to a broad audience. Accordingly, as the legal guardian, it is your responsibility to determine whether any of the Service areas and/or Content (as defined in Section 6 below) are appropriate for your child.
</p>

<h4>1Mile PRIVACY POLICY</h4>
<p>Registration Data and certain other information about you is subject to our Privacy Policy. For more information, see our full privacy policy at 1Mile Privacy Policy, or if you came from 1Mile Kids, then see our 1Mile Kids privacy policy at http://www.yahooligans.com/docs/privacy/. You understand that through your use of the Service you consent to the collection and use (as set forth in the Privacy Policy) of this information, including the transfer of this information to the United States and/or other countries for storage, processing and use by 1Mile and its affiliates.
</p>

<h4>MEMBER ACCOUNT, PASSWORD AND SECURITY</h4>
<p>You will receive a password and account designation upon completing the Service's registration process. You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your password or account. You agree to (a) immediately notify 1Mile of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. 1Mile cannot and will not be liable for any loss or damage arising from your failure to comply with this Section 5.
</p>	
