package common.amazon.aws;

public enum AwsSearchIndex {
    All
    , Apparel
    , Automotive
    , Baby
    , Beauty
    , Blended
    , Books
    , Classical
    , DigitalMusic
    , DVD
    , Electronics
    , ForeignBooks
    , GourmetFood
    , Grocery
    , HealthPersonalCare
    , Hobbies
    , HomeGarden
    , HomeImprovement
    , Industrial
    , Jewelry
    , KindleStore
    , Kitchen
    , Lighting
    , Magazines
    , Merchants
    , Miscellaneous
    , MP3Downloads
    , Music
    , MusicalInstruments
    , MusicTracks
    , OfficeProducts
    , OutdoorLiving
    , Outlet
    , PCHardware
    , PetSupplies
    , Photo
    , Shoes
    , Software
    , SoftwareVideoGames
    , SportingGoods
    , Tools
    , Toys
    , UnboxVideo
    , VHS
    , Video
    , VideoGames
    , Watches
    , Wireless
    , WirelessAccessories;
}
